name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
   deploy:
       env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
    
       runs-on: self-hosted

       steps: 
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run Docker Compose
          run: docker compose up -d --build