1  # This is workflow name
2  name: Hello
3  
4  # runs on a trigger
5  on:
6    push:
7      branches: [main]
8  
9  # these are inside the workflow
10 jobs:
11 
12   # this is the name of the job
13   greet:
14     # this is github runner, each job runs on a runner
15     runs-on: ubuntu-latest
16     steps:
17       - name: say hello to users
18         run: echo "Hello Devs"
19 
20       - name: say hello to username
21         run: echo "Hello $USER"
22
