name: Portfolio

on:
  push:
    branches: ["main"]
  workflow_dispatch:  

permissions:
  pages: write
  id-token: write    

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 

    steps:
      # STEP 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        
      # STEP 2: Setup github pages
      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5 
        
      # STEP 3: Upload Static Code Artifact
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: "." # Uploads index.html from the root folder

      # STEP 4: Makes pages live
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
